version: '3'

services:

    spark-master:
        image:
           "bde2020/spark-master:2.4.0-hadoop2.7"
        environment:
           - ENABLE_INIT_DAEMON=false
        ports:
           - 8080:8080
           - 7077:7077
        volumes:
           - ../../../src/:/app/
           - ../../../conf/spark-defaults.conf:/spark/conf/spark-defaults.conf
           - ../../../lib/:/app/htm/
           - ../../../lib/mysql-connector-java-8.0.13.jar:/spark/jars/mysql-connector-java-8.0.13.jar

