version: '3'

networks:

    # Internal network
    spark-master_default:


services:

    spark-worker:
        image:
            "bde2020/spark-worker:2.4.0-hadoop2.7"
        environment:
           - ENABLE_INIT_DAEMON=false
        volumes:
           - ../../../lib/mysql-connector-java-8.0.13.jar:/spark/jars/mysql-connector-java-8.0.13.jar
